#!/bin/bash
ACCOUNTID=$(aws sts get-caller-identity --query Account --output text)
aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ACCOUNTID.dkr.ecr.us-east-1.amazonaws.com
docker build -t $ACCOUNTID.dkr.ecr.us-east-1.amazonaws.com/prod-searchneu .
docker push $ACCOUNTID.dkr.ecr.us-east-1.amazonaws.com/prod-searchneu