#!/bin/bash

if [[ ! " prod staging " =~ " $1 " ]]; then
  echo "Please provide environment to use: prod or staging"
  exit 1
fi
CLUSTER="$1-searchneu"
SERVICES=( "$CLUSTER-webserver" "$CLUSTER-update" )

# Disable aws from sending stdout to less
export AWS_PAGER=""

echo "Redeploying cluster $CLUSTER with last pushed image"

if [[ "prod" = "$1" ]]; then
  # Check if prod and staging tag are already at the same point
  IMAGE_META="$( aws ecr describe-images --repository-name searchneu --image-ids imageTag=staging,imageTag=prod 2> /dev/null )"
  # If not, add prod tag to staging image
  if [[ $? -ne 0 ]]; then
    echo "Adding prod tag to staging image"
    MANIFEST=$(aws ecr batch-get-image --repository-name searchneu --image-ids imageTag=staging --query 'images[].imageManifest' --output text)
    aws ecr put-image --repository-name searchneu --image-tag prod --image-manifest "$MANIFEST"
  fi
fi

echo "Forcing new deployment"
for s in "${SERVICES[@]}"
do
  aws ecs update-service --cluster $CLUSTER --service $s --force-new-deployment  > /dev/null
done
echo "Check AWS Console for logs"